### ISSUE TITLE
模型版本更新了，但必须用1.2.7，怎么修复这个问题？

### ISSUE THREAD

**Issue by hacksoul0808** [liuzhao1225/YouDub-webui#3]
H:\AI\YouDub-webui\venv\Scripts\python.exe H:\AI\YouDub-webui\app.py 
torchvision is not available - cannot save figures
Lightning automatically upgraded your loaded checkpoint from v1.2.7 to v2.2.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\Administrator\.cache\torch\pyannote\models--pyannote--embedding\snapshots\c6335d8f1cd77b30084387468a6cf26fea90009b\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.8.1+cu102, yours is 2.0.1+cpu. Bad things might happen unless you revert torch to 1.x.
Lightning automatically upgraded your loaded checkpoint from v1.2.7 to v2.2.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\Administrator\.cache\torch\pyannote\models--pyannote--embedding\snapshots\c6335d8f1cd77b30084387468a6cf26fea90009b\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.8.1+cu102, yours is 2.0.1+cpu. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "H:\AI\YouDub-webui\app.py", line 6, in <module>
    from youdub.step040_tts import generate_all_wavs_under_folder
  File "H:\AI\YouDub-webui\youdub\step040_tts.py", line 11, in <module>
    from .step042_tts_xtts import tts as xtts_tts
  File "H:\AI\YouDub-webui\youdub\step042_tts_xtts.py", line 2, in <module>
    from TTS.api import TTS
ModuleNotFoundError: No module named 'TTS'

进程已结束，退出代码为 1

**Comment by 179909067** [comment]
自动下载下不来，怎么解决

**Comment by liuzhao1225** [comment]
项目已完全重构（新栈：FastAPI + Next.js + openai-whisper + spaCy + VoxCPM2 + OpenAI 兼容 API），原代码与依赖已不存在，本 issue 不再适用，关闭。

如果在新版本上仍遇到问题，欢迎参考最新 README 重新部署后再新开 issue。
